### PR TITLE
Update stripper.sp

### PR DESCRIPTION
**Pull request by pedrotski**
Some minor changes. 

The major one being it modifies the default file paths to be in line with the original Stripper Source so it ends up being a drop-in replacement.

### CODE REVIEW

**Comment by tilgep** [comment]
Can you match the indentation (4 spaces I believe), its hard to see what has actually been added.

**Review by tilgep — COMMENTED** [review]
See other comment

**Comment by Rushaway** [comment]
Here's the a proper diff checker of this PR.
https://www.diffchecker.com/QzRNGZH3/

**Comment by Rushaway** [comment]
@pedrotski I think it's a bad way to move, the current configs are related to sourcemod path because it's a sourcemod plugin.

**Comment by Vauff** [comment]
Yeah, the only reason original stripper used `addons/stripper` was because it was a Metamod plugin, same as SourceMod is. As a SourceMod plugin, that isn't really a correct pattern, and the current paths make sense for this. The other changes seem good though.

**Comment by pedrotski** [comment]
It's up to you if you want to accept it or not. Everyone I knew who used it wanted our fork, as it's a drop-in replacement.

**Comment by Vauff** [comment]
Hm, well I can see the case for that. Perhaps it may make sense to just add those as secondary loading paths for backwards compatibility purposes. Ultimately up to tilgep though.

**Comment by tilgep** [comment]
Personally I would want to move completely away from the `addons/stripper/` folder if I was switching to avoid confusion but each to their own.
I think it would be better to have a root directory as a cvar then instead of forcing something on people, and I think loading configs from multiple places should be avoided to prevent confusion.

**Comment by Rushaway** [comment]
Any updates? :)

**Pull request closed without merging**
